language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel

  ## Tagging
  - docker tag udagram-api-feed loctrinh17/udagram-api-feed:v1
  - docker tag udagram-api-user loctrinh17/udagram-api-user:v1
  - docker tag udagram-frontend:local loctrinh17/udagram-frontend:v2
  - docker tag reverseproxy loctrinh17/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push loctrinh17/udagram-api-feed:v1
  - docker push loctrinh17/udagram-api-user:v1
  - docker push loctrinh17/udagram-frontend:v2
  - docker push loctrinh17/reverseproxy:v1