language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel

  ## Tagging
  - docker tag udagram-api-feed khuongph/udagram-api-feed:v1
  - docker tag udagram-api-user khuongph/udagram-api-user:v1
  - docker tag udagram-frontend:local khuongph/udagram-frontend:v2
  - docker tag reverseproxy khuongph/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push khuongph/udagram-api-feed:v1
  - docker push khuongph/udagram-api-user:v1
  - docker push khuongph/udagram-frontend:v2
  - docker push khuongph/reverseproxy:v1